In [173]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.cluster import DBSCAN
from sklearn.cluster import AgglomerativeClustering

In [174]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [175]:
test=pd.read_csv("test.csv")
train=pd.read_csv("train.csv")

print(test.shape)
print(train.shape)

(1459, 80)
(1460, 81)

In [176]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [177]:
data=[train,test]
col=[]
for df in data:
    print(df['MSZoning'].unique())
    col.append(df.columns)
train.shape

['RL' 'RM' 'C (all)' 'FV' 'RH']
['RH' 'RL' 'RM' 'FV' 'C (all)' nan]

(1460, 81)

In [178]:
data=[train,test]
#print(col)
for df in data:
    print(df.isnull().sum().sort_values(ascending=False))
#print(train['Alley'].isnull().sum())

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
FireplaceQu       690
                 ...
CentralAir          0
SaleCondition       0
Heating             0
TotalBsmtSF         0
Id                  0
Length: 81, dtype: int64
PoolQC         1456
MiscFeature    1408
Alley          1352
Fence          1169
FireplaceQu     730
               ...
Electrical        0
CentralAir        0
HeatingQC         0
Foundation        0
Id                0
Length: 80, dtype: int64

In [179]:
z={}
col=df.columns
for i in col:
   # print(i)
    z[i]=((((train[i].isnull().sum())/len(train))*100))
for i ,j in z.items():
    if(j>30):
        test.drop(i,inplace=True,axis=1)
        train.drop(i,inplace=True,axis=1)
        #z.pop(i)
print(test.shape)
print(train.shape)
z2={}
for i in test.columns:
    z2[i]=((((test[i].isnull().sum())/len(test))*100))
for i ,j in z2.items():
    if(j>30):
        test.drop(i,inplace=True,axis=1)
        train.drop(i,inplace=True,axis=1)
        z2.pop(i)
print(test.shape)
print(train.shape)

(1459, 75)
(1460, 76)
(1459, 75)
(1460, 76)

In [180]:
for i in train.columns:
    if(train[i].isnull().sum()>0):
        train[i].fillna(method="bfill",inplace=True)
for i in test.columns:
    if(test[i].isnull().sum()>0):
        test[i].fillna(method="bfill",inplace=True)

In [181]:
train.isnull().sum().sort_values(ascending = False)/len(train)*100

SalePrice       0.0
ExterCond       0.0
RoofStyle       0.0
RoofMatl        0.0
Exterior1st     0.0
               ...
KitchenAbvGr    0.0
KitchenQual     0.0
TotRmsAbvGrd    0.0
Functional      0.0
Id              0.0
Length: 76, dtype: float64

In [182]:
test.isnull().sum().sort_values(ascending = False)/len(test)*100

SaleCondition    0.0
YearBuilt        0.0
RoofStyle        0.0
RoofMatl         0.0
Exterior1st      0.0
                ...
BedroomAbvGr     0.0
KitchenAbvGr     0.0
KitchenQual      0.0
TotRmsAbvGrd     0.0
Id               0.0
Length: 75, dtype: float64

In [184]:
from sklearn.preprocessing import LabelEncoder
categorical = [f for f in train.columns if train.dtypes[f] == 'object']
train[categorical]=train[categorical].apply(LabelEncoder().fit_transform)
categorical_test = [f for f in test.columns if test.dtypes[f] == 'object']
test[categorical_test]=test[categorical_test].apply(LabelEncoder().fit_transform)

In [185]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,0,0,0,0,0,12,2008,8,4,250000

In [186]:
train[categorical]

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,3,1,3,3,0,4,0,5,2,2,...,4,2,6,1,1,4,4,2,8,4
1,3,1,3,3,0,2,0,24,1,2,...,4,3,6,1,1,4,4,2,8,4
2,3,1,0,3,0,4,0,5,2,2,...,4,2,6,1,1,4,4,2,8,4
3,3,1,0,3,0,0,0,6,2,2,...,4,2,6,5,2,4,4,2,8,0
4,3,1,0,3,0,2,0,15,2,2,...,4,2,6,1,1,4,4,2,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,3,1,3,3,0,4,0,8,2,2,...,4,3,6,1,1,4,4,2,8,4
1456,3,1,3,3,0,4,0,14,2,2,...,4,3,2,1,2,4,4,2,8,4
1457,3,1,3,3,0,4,0,6,2,2,...,4,2,6,1,1,4,4,2,8,4
1458,3,1,3,3,0,4,0,12,2,2,...,0,2,6,1,2,4,4,2,8,4
1459,3,1,3,3,0,4,0,7,2,2,...,4,3,6,1,0,4,4,2,8,4

In [189]:
from sklearn.preprocessing import MinMaxScaler;
mi=MinMaxScaler();
train_df=pd.DataFrame(mi.fit_transform(train))
train_df.columns=train.columns
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0.000000,0.235294,0.75,0.150685,0.033420,1.0,1.0,1.0,0.0,1.0,...,0.000000,0.0,0.0,0.0,0.0,0.090909,0.50,1.0,0.8,0.241078
1,0.000685,0.000000,0.75,0.202055,0.038795,1.0,1.0,1.0,0.0,0.5,...,0.000000,0.0,0.0,0.0,0.0,0.363636,0.25,1.0,0.8,0.203583
2,0.001371,0.235294,0.75,0.160959,0.046507,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.0,0.0,0.0,0.0,0.727273,0.50,1.0,0.8,0.261908
3,0.002056,0.294118,0.75,0.133562,0.038561,1.0,0.0,1.0,0.0,0.0,...,0.492754,0.0,0.0,0.0,0.0,0.090909,0.00,1.0,0.0,0.145952
4,0.002742,0.235294,0.75,0.215753,0.060576,1.0,0.0,1.0,0.0,0.5,...,0.000000,0.0,0.0,0.0,0.0,1.000000,0.50,1.0,0.8,0.298709

In [196]:
test_df=pd.DataFrame(mi.fit_transform(test))
test_df.columns=test.columns
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0.000000,0.000000,0.50,0.329609,0.184147,1.0,1.0,1.000000,0.0,1.0,...,0.000000,0.0,0.0,0.208333,0.0,0.000000,0.454545,1.0,1.0,0.8
1,0.000686,0.000000,0.75,0.335196,0.232124,1.0,0.0,1.000000,0.0,0.0,...,0.048518,0.0,0.0,0.000000,0.0,0.735294,0.454545,1.0,1.0,0.8
2,0.001372,0.235294,0.75,0.296089,0.224197,1.0,0.0,1.000000,0.0,1.0,...,0.045822,0.0,0.0,0.000000,0.0,0.000000,0.181818,1.0,1.0,0.8
3,0.002058,0.235294,0.75,0.318436,0.154326,1.0,0.0,1.000000,0.0,1.0,...,0.048518,0.0,0.0,0.000000,0.0,0.000000,0.454545,1.0,1.0,0.8
4,0.002743,0.588235,0.75,0.122905,0.064121,1.0,0.0,0.333333,0.0,1.0,...,0.110512,0.0,0.0,0.250000,0.0,0.000000,0.000000,1.0,1.0,0.8

In [200]:
x=train_df.iloc[:,:-1]
y=train_df.iloc[:,-1:]

In [202]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
xgb = XGBRegressor()
parameters = {'objective':['reg:squarederror'],
            'learning_rate': [.1],
              'max_depth': [3],
              'min_child_weight': [2],
              'subsample': [0.7],
              'colsample_bytree': [.7],
              'colsample_bylevel':[.7],
              'alpha' : [.05],
              'lambda' : [.3],
              'n_estimators': [2500]}
XGB = GridSearchCV(xgb,
                        parameters,
                        cv = 2)
XGB.fit(x,y)

GridSearchCV(cv=2,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, gamma=None,
                                    gpu_id=None, importance_type='gain',
                                    interaction_constraints=None,
                                    learning_rate=None, max_delta_step=None,
                                    max_depth=None, min_child_weight=None,
                                    missing=nan, monotone_constraints=None,
                                    n_estimators=100, n_jobs=...
                                    reg_alpha=None, reg_lambda=None,
                                    scale_pos_weight=None, subsample=None,
                                    tree_method=None, validate_parameters=None,
                                    verbosity=None),
             param_grid={'alpha': [0.05], 'colsample_bylevel': [0.7],
                         'colsample_bytree': [0.7], 'lambda': [0.3],
                         'learning_rate': [0.1], 'max_depth': [3],
                         'min_child_weight': [2], 'n_estimators': [2500],
                         'objective': ['reg:squarederror'],
                         'subsample': [0.7]})

In [203]:
XGB.best_params_

{'alpha': 0.05,
 'colsample_bylevel': 0.7,
 'colsample_bytree': 0.7,
 'lambda': 0.3,
 'learning_rate': 0.1,
 'max_depth': 3,
 'min_child_weight': 2,
 'n_estimators': 2500,
 'objective': 'reg:squarederror',
 'subsample': 0.7}

In [205]:
XGB.best_score_

0.8730858637556582

In [206]:
x_test=test_df

In [211]:
y_pred = XGB.predict(x_test)
y_pred

array([0.16660306, 0.20454678, 0.2300697 , ..., 0.19655216, 0.13723108,
       0.28817195], dtype=float32)

In [212]:
submission = pd.DataFrame({
        "Id": test_df.Id,
        "SalePrice": y_pred
    })
submission.to_csv('first_submission.csv', index=False)

In [214]:
submission.head(100)

          Id  SalePrice
0   0.000000   0.166603
1   0.000686   0.204547
2   0.001372   0.230070
3   0.002058   0.243903
4   0.002743   0.239772
..       ...        ...
95  0.065158   0.093840
96  0.065844   0.100297
97  0.066529   0.101430
98  0.067215   0.085887
99  0.067901   0.156311

[100 rows x 2 columns]